behaviors:
  CubeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.99
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    max_steps: 5.0e6
    time_horizon: 128
    summary_freq: 5000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true