behaviors:
  RunnerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 0.008
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.995
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    max_steps: 5.0e6
    time_horizon: 256
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true