# Train Runner and Tagger together in one session.
# Launch with:
#   mlagents-learn Assets/ML-Agents/Configs/selfplay_combo.yaml --run-id=tag_selfplay_01 --train
behaviors:
  RunnerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 0.008
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.995
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    max_steps: 6.0e6
    time_horizon: 256
    summary_freq: 10000
    threaded: true

  TaggerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 0.008
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.995
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    max_steps: 6.0e6
    time_horizon: 256
    summary_freq: 10000
    threaded: true