behaviors:
  RunnerAgent:
    trainer_type: ppo
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 0.008
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.995
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    max_steps: 1.0e7
    time_horizon: 256
    summary_freq: 10000